import type { AttachmentStyleName, LifeFacetsImpact } from '../types/jyotish.ts';

export interface KetuHouseTrajectory {
  houseNumber: number;
  axisTitle: string;
  exileSomaticFascia: string;
  exileCoreDread: string;
  pastLifeSurvivalGenius: string;
  facets: LifeFacetsImpact;
  realWorldTuesdayScenario: {
    workplace: string;
    money: string;
    creative: string;
    somatic: string;
    family: string;
    solitude: string;
    romance: string;
  };
}

export const KETU_HOUSE_DATA: Record<number, KetuHouseTrajectory> = {
  1: {
    houseNumber: 1,
    axisTitle: 'First Bhava (Tanu) ➔ Seventh Bhava (Yuvati)',
    exileSomaticFascia: 'cranial base, facial masking muscles, and upper cervical spine',
    exileCoreDread: 'that revealing raw individuality or bodily vulnerability will provoke hostile rejection or isolation',
    pastLifeSurvivalGenius: 'fierce, solitary survival where you could rely on no one other than your own physical wits and self-containment',
    facets: {
      vocationAndMoney: 'You operate as a solitary force; accepting advice or capital from others feels like giving away the steering wheel of your life.',
      creativeVoiceAndVisibility: 'Deep fear of being mischaracterized or diluted; you guard your personal brand with ferocious territoriality.',
      somaticHealthAndNervousSystem: 'Nervous system stays braced in the neck and jaw; you project an invulnerable physical presence while running on empty.',
      familyLineageAndAncestralRoles: 'Historically the self-reliant outsider in the family who was never allowed to show physical or emotional weakness.',
      existentialTrustAndSolitude: 'You retreat into self-sufficient hermitage, viewing the outside world as demanding and intrusive.',
      interpersonalAndRomanticBonds: 'Hyper-vigilant defense of personal boundaries; fearing that intimacy will swallow your autonomy alive.',
    },
    realWorldTuesdayScenario: {
      workplace: 'When a colleague or manager suggests a modification to your workflow, your body immediately tenses as if your fundamental competence is under attack, driving you to defend your process with cold, unyielding rigidity.',
      money: 'You maintain strictly independent accounts and emergency reserves, feeling uneasy about any shared financial liability or joint business venture.',
      creative: 'You delay launching creative endeavors until you have authored every single detail yourself, refusing collaboration even when a teammate could save you months.',
      somatic: 'Your neck muscles lock up by mid-afternoon, and you hold your breath whenever forced to sit through unstructured committee debates.',
      family: 'You show up to family obligations as an impenetrable, self-sufficient adult, sharing none of your current struggles with parents or siblings.',
      solitude: 'You take comfort in solitary late-night hours where nobody expects you to respond, negotiate, or explain yourself.',
      romance: 'When a partner asks to spend an entire weekend together without scheduled breaks, a silent wave of claustrophobia washes over you.',
    },
  },
  2: {
    houseNumber: 2,
    axisTitle: 'Second Bhava (Dhana) ➔ Eighth Bhava (Randhra)',
    exileSomaticFascia: 'throat chakra, vocal cords, thyroid, and mandibular joints',
    exileCoreDread: 'sudden poverty, material starvation, voicelessness, or exile from family resources',
    pastLifeSurvivalGenius: 'mastery of resource preservation, liquid capital accumulation, and conservative oral restraint',
    facets: {
      vocationAndMoney: 'You hold onto every dollar out of survival terror; no matter how large your savings grow, the fear of bankruptcy never fully dissipates.',
      creativeVoiceAndVisibility: 'Speech hesitation; swallowing your rawest, most radical insights because speaking out might cost you material security.',
      somaticHealthAndNervousSystem: 'Chronic throat constriction, teeth grinding at night, and digestive tightness around food intake and metabolism.',
      familyLineageAndAncestralRoles: 'Carrying the financial anxieties and intergenerational scarcity programming of ancestors who survived deprivation.',
      existentialTrustAndSolitude: 'Struggling to trust the universe for sustenance; believing that your bank account balance is the only true god.',
      interpersonalAndRomanticBonds: 'Evaluating partners through the lens of material stability and predictability, dreading that an extravagant partner will ruin you.',
    },
    realWorldTuesdayScenario: {
      workplace: 'In salary reviews or client pricing, an invisible clamp tightens around your throat, making it excruciatingly difficult to ask for your market value without apologizing.',
      money: 'An unexpected $400 car maintenance bill or minor investment dip triggers an immediate internal panic as if your entire household security is collapsing.',
      creative: 'You edit your writings or business pitches to sound conservative and universally palatable, filtering out controversial viewpoints that could alienate clients.',
      somatic: 'You wake up with a sore jaw and tension in your throat, noticing how tightly you hold your breath whenever reviewing bank statements.',
      family: 'You feel compelled to manage or monitor family assets and inheritance conversations, terrified that relatives will squander the lineage capital.',
      solitude: 'Even during vacation downtime, your mind runs financial calculations, mentally auditing your asset allocation and projected expenses.',
      romance: 'You find it difficult to spend money on spontaneous romantic getaways or luxury without experiencing immediate buyer remorse.',
    },
  },
  3: {
    houseNumber: 3,
    axisTitle: 'Third Bhava (Sahaja) ➔ Ninth Bhava (Dharma)',
    exileSomaticFascia: 'shoulders, arms, hands, and upper bronchia',
    exileCoreDread: 'being intellectually humiliated, commercially outmaneuvered, silenced, or paralyzed at the moment of execution',
    pastLifeSurvivalGenius: 'tactical cunning, rapid intellectual agility, persuasive rhetoric, and relentless small-scale commercial hustle',
    facets: {
      vocationAndMoney: 'Addicted to the daily grind; you believe you must personally hustle, out-write, and out-work every competitor to stay afloat.',
      creativeVoiceAndVisibility: 'Obsessive wordsmithing; endlessly polishing sentences and tactical details while avoiding the larger visionary horizon.',
      somaticHealthAndNervousSystem: 'Upper respiratory tension, shallow hyper-ventilation, and nervous twitching in fingers from non-stop digital execution.',
      familyLineageAndAncestralRoles: 'Sibling rivalry or peer comparison scars; feeling you were judged strictly on cleverness and verbal agility.',
      existentialTrustAndSolitude: 'A hyperactive, chattering mind that fears quiet stillness because stillness feels like falling behind in the race.',
      interpersonalAndRomanticBonds: 'Using debates, intellectual banter, and clever humor to keep people at a safe emotional distance.',
    },
    realWorldTuesdayScenario: {
      workplace: 'You spend four hours obsessing over the syntax of a brief client email, analyzing how each phrase might be interpreted or weaponized against you.',
      money: 'You maintain multiple micro-income streams and side-hustles, feeling anxious whenever you rely on a single primary revenue contract.',
      creative: 'You hoard dozens of unfinished articles, pitches, and creative fragments in notebooks, terrified of releasing them before they are bulletproof.',
      somatic: 'Your shoulders creep toward your ears as you type furiously, and you experience afternoon headaches from visual and mental over-exertion.',
      family: 'You feel a reflexive urge to prove your intellectual or professional credentials whenever speaking with siblings or extended relatives.',
      solitude: 'Sitting quietly without a book, phone, or podcast makes you deeply anxious, triggering a rush of guilt that you are wasting valuable time.',
      romance: 'During relationship disagreements, you treat arguments like a courtroom trial, cross-examining your partner with airtight logical arguments.',
    },
  },
  4: {
    houseNumber: 4,
    axisTitle: 'Fourth Bhava (Sukha) ➔ Tenth Bhava (Karma)',
    exileSomaticFascia: 'sub-diaphragmatic fascia, solar plexus, and lower rib cage',
    exileCoreDread: 'that your domestic foundation and inner sanctuary will be shattered, leaving you emotionally displaced and exposed',
    pastLifeSurvivalGenius: 'creating fortified emotional sanctuaries, private retreats, and enduring intense maternal or domestic turbulence in silence',
    facets: {
      vocationAndMoney: 'You retreat into comfort zones; public career exposure feels like leaving your safe bunker and walking into sniper fire.',
      creativeVoiceAndVisibility: 'Deeply intimate, soulful creative impulses that you hesitate to expose to the cold commercial marketplace.',
      somaticHealthAndNervousSystem: 'Visceral gut clenching, digestive sensitivity, and sudden emotional fatigue when the home environment is unsettled.',
      familyLineageAndAncestralRoles: 'The emotional sponge of the home; carrying the ancestral sorrow, mothering wounds, and domestic burdens of the lineage.',
      existentialTrustAndSolitude: 'Craving deep emotional sanctuary while secretly believing that genuine peace of mind is an impossible illusion.',
      interpersonalAndRomanticBonds: 'Testing whether a partner will provide absolute emotional safety, retreating into a shell whenever friction threatens the nest.',
    },
    realWorldTuesdayScenario: {
      workplace: 'When an opportunity for public leadership, executive visibility, or conference speaking arrives, an intense urge to stay in your private home office takes over.',
      money: 'You prioritize real estate, home equity, and physical domestic provisions above all speculative growth, needing your dwelling to be an unshakeable fortress.',
      creative: 'Your best ideas are written in private journals late at night, but you shudder at the thought of putting your face and name on a public billboard.',
      somatic: 'When domestic conflict or a moving transition occurs, your digestion immediately shuts down and your lower ribs feel tightly bound.',
      family: 'You feel an involuntary compulsion to manage your parents’ emotional well-being, feeling responsible for the peace of the family home.',
      solitude: 'Your home is your sacred hermitage; when outside guests or chaotic obligations disrupt your private sanctuary, you feel depleted for days.',
      romance: 'When a partner is emotionally distant or irritable after work, you automatically assume the home atmosphere is ruined and retreat into silence.',
    },
  },
  5: {
    houseNumber: 5,
    axisTitle: 'Fifth Bhava (Putra) ➔ Eleventh Bhava (Labha)',
    exileSomaticFascia: 'cardiac center, pericardium, and thoracic spine',
    exileCoreDread: 'being publicly mocked, creatively humiliated, betrayed by loved ones, or having your unique genius cast aside',
    pastLifeSurvivalGenius: 'pure aristocratic self-expression, private creative mastery, speculative instinct, and sovereign heart-authorship',
    facets: {
      vocationAndMoney: 'You demand total creative control; you struggle to work in large corporate committees where your creative voice is averaged out.',
      creativeVoiceAndVisibility: 'Perfectionist protection of your artistic or entrepreneurial creations; treating your work like a vulnerable child.',
      somaticHealthAndNervousSystem: 'Heart palpitations, chest tightness under creative scrutiny, and emotional burnout when romantic joy is withheld.',
      familyLineageAndAncestralRoles: 'Carrying the burden of being the exceptional or gifted family member who had to validate the family’s worth.',
      existentialTrustAndSolitude: 'Struggling when not recognized as unique; feeling a profound existential ache when treated like just another face in the crowd.',
      interpersonalAndRomanticBonds: 'Intense romantic vulnerability; longing for grand devotion but terrified of having your open heart crushed.',
    },
    realWorldTuesdayScenario: {
      workplace: 'If a client or boss redlines your creative proposal without acknowledging its brilliance, you experience a visceral sting of rejection and disengage.',
      money: 'You swing between conservative caution and bold speculative bets on your own ideas, wanting your wealth to be born of pure genius.',
      creative: 'You spend six months refining a single creative artifact in secret, terrified that presenting an imperfect draft will brand you as amateur.',
      somatic: 'Before presenting creative work or speaking from the heart, your heart pounds rapidly against your ribs and your breath becomes shallow.',
      family: 'You felt pressure to be the bright star of the family lineage, internalizing the belief that love is conditional upon performance and flair.',
      solitude: 'Solitude is where your creative imagination flourishes, but it can turn melancholic if you feel your gifts are unappreciated by the world.',
      romance: 'You shower romantic partners with intense, theatrical devotion, but the moment you sense lukewarm reciprocity, you withdraw into wounded pride.',
    },
  },
  6: {
    houseNumber: 6,
    axisTitle: 'Sixth Bhava (Ripu) ➔ Twelfth Bhava (Vyaya)',
    exileSomaticFascia: 'gut microbiome, abdominal fascia, and adrenal glands',
    exileCoreDread: 'being crushed by chaos, chronic debt, physical infirmity, administrative failure, or workplace conflict',
    pastLifeSurvivalGenius: 'tireless diagnostic scrutiny, crisis containment, systemic boundary enforcement, and surviving hostile environments',
    facets: {
      vocationAndMoney: 'The compulsive fixer; you take on toxic operational messes, working inhuman hours to keep organizational entropy at bay.',
      creativeVoiceAndVisibility: 'Hyper-critical editing; you spot every microscopic flaw in your output, often paralyzing your ability to publish.',
      somaticHealthAndNervousSystem: 'Chronic digestive sensitivity, adrenal strain, and immune over-reactivity from living in a state of endless emergency preparedness.',
      familyLineageAndAncestralRoles: 'The family problem-solver who was summoned whenever legal, financial, or medical catastrophes occurred.',
      existentialTrustAndSolitude: 'Difficulty surrendering to rest; you feel guilty when relaxing, convinced that an undetected disaster is brewing while you sleep.',
      interpersonalAndRomanticBonds: 'Treating relationships as problems to be debugged, analyzing partner behavior with diagnostic scrutiny rather than soft empathy.',
    },
    realWorldTuesdayScenario: {
      workplace: 'You spend your Friday evening combing through technical documentation or administrative spreadsheets, convinced that if you don’t catch the error, catastrophe will follow.',
      money: 'You obsess over debt elimination, insurance policies, and risk mitigation, feeling that financial ease is a trap designed to make you complacent.',
      creative: 'You rewrite an outline eight times because of small structural imperfections, letting months pass without publishing the completed work.',
      somatic: 'Your stomach churns with acid when an unexpected dispute arises at work, and your digestive system reflects every micro-stressor of the week.',
      family: 'Relatives call you only when their lives are on fire because they know you will organize the lawyers, doctors, and logistics without complaint.',
      solitude: 'When you take a day off, you clean the entire house, organize digital files, or run errands, unable to sit in unstructured stillness.',
      romance: 'During intimate moments, your mind notices that the kitchen sink is dripping or that your partner hasn’t scheduled their dentist checkup.',
    },
  },
  7: {
    houseNumber: 7,
    axisTitle: 'Seventh Bhava (Yuvati) ➔ First Bhava (Tanu)',
    exileSomaticFascia: 'sacrum, lower lumbar spine, kidneys, and pelvic floor',
    exileCoreDread: 'being betrayed, displaced, or spiritually devoured by business partners or intimate spouses once fully committed',
    pastLifeSurvivalGenius: 'exquisite diplomacy, mirror-attunement, negotiating hostile contracts, and surviving through dyadic alliances',
    facets: {
      vocationAndMoney: 'You tie your professional destiny to partners and co-founders, then resent the loss of autonomy when their vision clashes with yours.',
      creativeVoiceAndVisibility: 'Compromising your creative voice to maintain harmony; watering down your radical opinions to avoid alienating collaborators.',
      somaticHealthAndNervousSystem: 'Lower back ache, pelvic tension, and adrenal depletion caused by chronic interpersonal attunement and conflict suppression.',
      familyLineageAndAncestralRoles: 'Conditioned to be the peace-keeper who smoothed over marital fractures between parents, sacrificing your own needs.',
      existentialTrustAndSolitude: 'Terrified of being utterly alone in the world, yet feeling suffocated and trapped whenever you are bound to another.',
      interpersonalAndRomanticBonds: 'The classic partnership dilemma: you over-compromise to keep the bond intact, until resentment forces an abrupt exit.',
    },
    realWorldTuesdayScenario: {
      workplace: 'In joint ventures, you find yourself doing 70% of the work while maintaining a 50/50 split because confronting your co-founder feels too dangerous.',
      money: 'You feel conflicted about joint bank accounts, fearing that your partner’s financial decisions will jeopardize your hard-earned security.',
      creative: 'You co-author or collaborate on projects where your distinctive voice is diluted, wishing you had the courage to release a solo monograph.',
      somatic: 'Your lower back seizes up whenever you swallow an unexpressed grievance with a business partner or spouse.',
      family: 'You find yourself mediating long-standing feuds between family members, acting as the neutral diplomat while exhausting your own spirit.',
      solitude: 'Being completely single or solitary triggers a subterranean panic that you are unmoored, yet being coupled triggers a desire for solitary escape.',
      romance: 'You silently keep score of emotional compromises, waiting for your partner to notice the imbalance without having to articulate your rage.',
    },
  },
  8: {
    houseNumber: 8,
    axisTitle: 'Eighth Bhava (Randhra) ➔ Second Bhava (Dhana)',
    exileSomaticFascia: 'pelvic bowl, reproductive organs, perineum, and deep psoas',
    exileCoreDread: 'catastrophic betrayal, sudden violent loss of control, economic ruin through hidden traps, or psychic annihilation',
    pastLifeSurvivalGenius: 'crisis alchemy, reading subterranean motives, surviving psychological warfare, and navigating life-and-death transitions',
    facets: {
      vocationAndMoney: 'You thrive in high-stakes turnaround environments, but carry perpetual suspicion that business partners harbor hidden agendas.',
      creativeVoiceAndVisibility: 'Subversive, intense, and psychologically penetrative voice; you refuse to make superficial art, but guard your secrets fiercely.',
      somaticHealthAndNervousSystem: 'Deep psoas tightness, reproductive tension, and chronic sympathetic vigilance scanning for psychological booby-traps.',
      familyLineageAndAncestralRoles: 'Carrying the unacknowledged lineage secrets, taboo grief, and traumatic bankruptcies of previous generations.',
      existentialTrustAndSolitude: 'Radical suspicion of surface appearances; you believe that anything that looks too good to be true is definitely a trap.',
      interpersonalAndRomanticBonds: 'Intense emotional intimacy tests; requiring absolute soul loyalty while holding your own final emotional keys in secret.',
    },
    realWorldTuesdayScenario: {
      workplace: 'When an executive team meeting ends, you spend the next hour analyzing the body language and micro-expressions of stakeholders to detect conspiracies.',
      money: 'You scrutinize contracts with a fine-toothed comb, looking for indemnification clauses or traps that could wipe out your assets in a worst-case scenario.',
      creative: 'You write profound, transformative manuscripts that dive into taboos, but keep them encrypted on a private hard drive away from public eyes.',
      somatic: 'Your psoas muscles remain permanently contracted, holding your body in a subtle crouch ready to dodge a psychological blow.',
      family: 'You are the only member of the lineage willing to look directly at the ancestral secrets—addictions, divorces, or hidden financial losses.',
      solitude: 'You find peace only in total secrecy, where nobody knows your location, your net worth, or your next strategic maneuver.',
      romance: 'You test lovers with intense psychological probing, waiting to see if their loyalty will crack when you reveal your darkest shadows.',
    },
  },
  9: {
    houseNumber: 9,
    axisTitle: 'Ninth Bhava (Dharma) ➔ Third Bhava (Sahaja)',
    exileSomaticFascia: 'hips, sciatic nerve pathways, and thighs',
    exileCoreDread: 'nihilistic disillusionment, dogmatic hypocrisy, spiritual betrayal by mentors, or discovering that life lacks moral meaning',
    pastLifeSurvivalGenius: 'philosophical mastery, moral integrity, adherence to higher codes, and navigating distant civilizations with ethical authority',
    facets: {
      vocationAndMoney: 'You demand ethical perfection from your work; you refuse lucrative commercial projects if they violate your philosophical principles.',
      creativeVoiceAndVisibility: 'Grand philosophical declarations; you write epic manifestos, but struggle with tactical everyday commercial marketing.',
      somaticHealthAndNervousSystem: 'Sciatic nerve flare-ups, hip tightness, and restlessness when confined to mundane administrative routines.',
      familyLineageAndAncestralRoles: 'The philosophical rebel who broke away from dogmatic family religions or cultural orthodoxy in search of universal truth.',
      existentialTrustAndSolitude: 'Longing for a cosmic home; feeling like an exile who belongs to no single nation, creed, or conventional institution.',
      interpersonalAndRomanticBonds: 'Looking for a spiritual equal or ideological comrade; feeling profoundly lonely when partners cannot engage in philosophical depth.',
    },
    realWorldTuesdayScenario: {
      workplace: 'You walk away from a lucrative commercial contract because the leadership team exhibited subtle ethical hypocrisy that offended your soul.',
      money: 'You treat money as a moral test, feeling uneasy about capital accumulation unless every dollar is tied to noble, virtuous impact.',
      creative: 'You write brilliant, comprehensive treatises on ethics and society, but hesitate to condense your thoughts into practical soundbites.',
      somatic: 'Your hips and lower back ache when sitting at a corporate desk executing repetitive data entry that feels spiritually meaningless.',
      family: 'Family dinners become minefields when relatives voice narrow, dogmatic prejudices, causing you to either lecture them or leave the table.',
      solitude: 'You seek solitude in distant travels, mountain sanctuaries, or ancient libraries, seeking solace in timeless philosophical traditions.',
      romance: 'When a romantic partner expresses shallow gossip or materialistic obsessions, an icy wall of philosophical judgment drops between you.',
    },
  },
  10: {
    houseNumber: 10,
    axisTitle: 'Tenth Bhava (Karma) ➔ Fourth Bhava (Sukha)',
    exileSomaticFascia: 'knees, skeletal frame, joint capsules, and upper shoulders',
    exileCoreDread: 'public disgrace, executive failure, career displacement, or having your human worth reduced strictly to your external productivity',
    pastLifeSurvivalGenius: 'relentless executive endurance, social status management, structural governance, and bearing the weight of public responsibility',
    facets: {
      vocationAndMoney: 'Workaholism as identity armor; you believe your right to breathe is contingent upon producing flawless, undeniable executive output.',
      creativeVoiceAndVisibility: 'Strictly professional, curated visibility; terrified of being seen as amateur, unpolished, or emotionally messy.',
      somaticHealthAndNervousSystem: 'Joint stiffness, knee pain, chronic skeletal fatigue, and adrenaline-driven endurance pushing through exhaustion.',
      familyLineageAndAncestralRoles: 'The family pride bearer; carrying the expectation that you must elevate the lineage status through public achievement.',
      existentialTrustAndSolitude: 'Struggling to relax without guilt; when away from work, you feel an aching emptiness as if your identity has vanished.',
      interpersonalAndRomanticBonds: 'Treating relationships like secondary appointments around your career master-plan; struggling with soft vulnerability at home.',
    },
    realWorldTuesdayScenario: {
      workplace: 'When a minor mistake occurs on an executive deliverable, your stomach drops into an abyss, convinced that your entire reputation is permanently ruined.',
      money: 'You measure financial safety through institutional standing, corporate titles, and public credibility rather than liquid ease.',
      creative: 'You only share creative work that has been vetted, peer-reviewed, or certified by recognized institutional authorities.',
      somatic: 'You force yourself into early morning workouts and late-night office hours through sheer willpower, ignoring severe physical joint fatigue.',
      family: 'You feel that you are only truly loved by parents or relatives when you bring home awards, credentials, or prestigious career milestones.',
      solitude: 'Taking a two-week vacation without a laptop causes severe anxiety; you check work notifications from the beach to prove you are indispensable.',
      romance: 'When your spouse asks you to unplug and connect emotionally on a Sunday afternoon, you feel restless and secretly wish you were in your study.',
    },
  },
  11: {
    houseNumber: 11,
    axisTitle: 'Eleventh Bhava (Labha) ➔ Fifth Bhava (Putra)',
    exileSomaticFascia: 'shins, calves, ankles, and peripheral nervous system',
    exileCoreDread: 'being ostracized by the group, marginalized from social networks, betrayed by allies, or remaining an unvalued outsider',
    pastLifeSurvivalGenius: 'large-scale community mobilization, network coordination, intellectual detachment, and navigating collective systems',
    facets: {
      vocationAndMoney: 'You build expansive professional networks and scale revenue pipelines, yet secretly feel that no single group truly cares about you.',
      creativeVoiceAndVisibility: 'Framing your work as a collective movement; you hesitate to stand center-stage as an individual solo author.',
      somaticHealthAndNervousSystem: 'Peripheral nervous agitation, ankle stiffness, circulation stagnation, and mental overload from managing too many connections.',
      familyLineageAndAncestralRoles: 'The progressive visionary in the family who was expected to represent the family in high-status social circles.',
      existentialTrustAndSolitude: 'Feeling lonely in a crowded room; you know hundreds of people, but have very few intimate soul confidants.',
      interpersonalAndRomanticBonds: 'Treating partners like peers in a cause or ideological comrades, struggling with direct, tender, one-on-one romance.',
    },
    realWorldTuesdayScenario: {
      workplace: 'You spend hours maintaining alliances across disparate departments, terrified that a shifting political coalition will leave you isolated.',
      money: 'You focus on network capital, equity pools, and passive distribution streams, but worry about being cut out of backend profits by partners.',
      creative: 'You launch community platforms or group ventures, but feel uncomfortable writing a deeply personal memoir that puts yourself center stage.',
      somatic: 'Your nervous system feels like a high-voltage electrical grid with too many open tabs, resulting in insomnia and restless legs at night.',
      family: 'You organize family reunions and group gatherings, acting as the social coordinator while maintaining an emotional buffer around yourself.',
      solitude: 'You surround yourself with Slack groups, community chats, and social feeds to avoid confronting the deep loneliness in your chest.',
      romance: 'Your romantic partner complains that they have to share you with your twenty friends and community causes, craving your undivided gaze.',
    },
  },
  12: {
    houseNumber: 12,
    axisTitle: 'Twelfth Bhava (Vyaya) ➔ Sixth Bhava (Ripu)',
    exileSomaticFascia: 'feet, lymphatic circulation, and pineal/melatonin sleep rhythms',
    exileCoreDread: 'dissolution, energetic bankruptcy, total isolation, or being forgotten and erased by the waking commercial world',
    pastLifeSurvivalGenius: 'mystical surrender, navigating altered states of consciousness, surviving institutional confinement, and deep transpersonal peace',
    facets: {
      vocationAndMoney: 'You feel alienated from commercial capitalism; you experience money as a confusing, crude necessity that drains your spiritual energy.',
      creativeVoiceAndVisibility: 'Ethereal, mythic, and transcendental creative voice; you produce hauntingly beautiful work that resists commercial packaging.',
      somaticHealthAndNervousSystem: 'Sleep disruptions, vivid nocturnal processing, lymphatic sluggishness, and sensory sensitivity to noisy environments.',
      familyLineageAndAncestralRoles: 'Carrying the grief of ancestors who were institutionalized, exiled, or who withdrew from the world in grief.',
      existentialTrustAndSolitude: 'Profound mystical comfort in total isolation, contrasted with exhaustion when navigating daily worldly logistics.',
      interpersonalAndRomanticBonds: 'Longing for a spiritual soul-merger; prone to unexpressed longing or idealizing partners who are unavailable.',
    },
    realWorldTuesdayScenario: {
      workplace: 'After a four-hour corporate meeting with competitive posturing, your energetic field feels completely drained and you need hours in a dark room to recover.',
      money: 'You experience subconscious guilt around accumulating wealth, sometimes letting money slip through your fingers as if holding it is spiritually unholy.',
      creative: 'You channel profound poetry, musical compositions, or visionary art in twilight states, but feel paralyzed when asked to create a marketing funnel.',
      somatic: 'You wake up at 4 AM feeling the collective sadness of the world, your feet cold and your nervous system floating ungrounded.',
      family: 'You are the member of the family who disappears into solitary retreats for weeks, needing total retreat from ancestral expectations.',
      solitude: 'Solitude is not a luxury for you—it is your oxygen; without regular periods of total silence, your mental health rapidly deteriorates.',
      romance: 'You fall in love with someone’s soul potential rather than their messy human reality, feeling heartbroken when everyday friction intrudes.',
    },
  },
};

export const POLARITY_DESCRIPTIONS: Record<string, {
  axisName: string;
  karmicCeiling: string;
  rahuEvolutionaryCall: string;
  facetsShift: LifeFacetsImpact;
}> = {
  '1-7': {
    axisName: 'The Axis of Sovereign Individuation (1st) to Sacred Interdependence (7th)',
    karmicCeiling: 'Staying trapped in solitary fortress mentality, viewing all compromise as existential defeat, and starving for true partnership.',
    rahuEvolutionaryCall: 'Risking transparent, peer-level agreements where you share the steering wheel without losing your sovereign core.',
    facetsShift: {
      vocationAndMoney: 'From a lone-wolf operator to building high-trust equity partnerships and joint commercial ventures that scale far beyond solo labor.',
      creativeVoiceAndVisibility: 'From guarded private authorship to co-creating with brilliant collaborators who mirror and sharpen your vision.',
      somaticHealthAndNervousSystem: 'Releasing the chronic neck and jaw bracing of self-containment; allowing your nervous system to coregulate with a trusted ally.',
      familyLineageAndAncestralRoles: 'Breaking the cycle of ancestral isolation; modeling an interdependent partnership where mutual support is safe.',
      existentialTrustAndSolitude: 'Recognizing that the divine is met not just in solitary meditation, but in the sacred crucible of another human soul.',
      interpersonalAndRomanticBonds: 'Surrendering the defensive test; asking for closeness and welcoming real interdependence without fear of engulfment.',
    },
  },
  '2-8': {
    axisName: 'The Axis of Concrete Capital (2nd) to Shared Metamorphosis (8th)',
    karmicCeiling: 'Clinging to rigid material hoarding, financial anxiety, and surface predictability while avoiding psychological transformation.',
    rahuEvolutionaryCall: 'Stepping into crisis alchemy, shared assets, psychological depth, and surrendering the illusion of total financial control.',
    facetsShift: {
      vocationAndMoney: 'From conservative hoarding to high-yield joint ventures, venture investments, and transforming distressed assets into power.',
      creativeVoiceAndVisibility: 'From polite, safe expressions to unflinching, psychologically penetrative truths that transform your audience.',
      somaticHealthAndNervousSystem: 'Releasing the chronic throat clamp and teeth-grinding; allowing deep pelvic and psoas release during emotional surrender.',
      familyLineageAndAncestralRoles: 'Healing ancestral financial taboos; metabolizing lineage grief rather than burying it under property titles.',
      existentialTrustAndSolitude: 'Trusting the cyclical death and rebirth of the universe; knowing that losing control is often the doorway to true spiritual power.',
      interpersonalAndRomanticBonds: 'Moving beyond surface domestic arrangements into profound soul-merging and total psychological transparency.',
    },
  },
  '3-9': {
    axisName: 'The Axis of Tactical Execution (3rd) to Sovereign Dharma (9th)',
    karmicCeiling: 'Drowning in endless micro-hustle, digital noise, tactical errands, and sibling rivalries while avoiding the grand visionary horizon.',
    rahuEvolutionaryCall: 'Claiming your philosophical authority, publishing your grand worldview, mentoring others, and expanding internationally.',
    facetsShift: {
      vocationAndMoney: 'From an underpaid tactical technician to a sought-after visionary, thought leader, or founder with global reach.',
      creativeVoiceAndVisibility: 'From fragmented short-form posts to authoring definitive, foundational monographs and institutional philosophies.',
      somaticHealthAndNervousSystem: 'Calming the frantic respiratory flutter and restless fingers; grounding consciousness in diaphragmatic depth and spacious ease.',
      familyLineageAndAncestralRoles: 'Stepping out of the small family sibling competition and becoming the wise, dignified elder of the lineage.',
      existentialTrustAndSolitude: 'Anchoring your life in an unshakeable ethical and spiritual framework that renders daily trivialities harmless.',
      interpersonalAndRomanticBonds: 'Engaging partners as philosophical companions and fellow horizon-seekers, releasing defensive intellectual debates.',
    },
  },
  '4-10': {
    axisName: 'The Axis of Domestic Sanctuary (4th) to Executive Stature (10th)',
    karmicCeiling: 'Hiding in the private domestic bunker, avoiding public leadership, and treating career visibility as a life-threatening danger.',
    rahuEvolutionaryCall: 'Stepping center-stage into executive mastery, public reputation, and building systems that lead society at scale.',
    facetsShift: {
      vocationAndMoney: 'From behind-the-scenes comfort to commanding executive presence, board leadership, and recognized industry authority.',
      creativeVoiceAndVisibility: 'Publishing your work on national and global stages, letting your face and name become synonymous with excellence.',
      somaticHealthAndNervousSystem: 'Releasing the sub-diaphragmatic gut clenching; learning that your body can handle public exposure with relaxed poise.',
      familyLineageAndAncestralRoles: 'Lifting the entire family lineage onto a higher plane of societal contribution without carrying their emotional baggage.',
      existentialTrustAndSolitude: 'Knowing that true sanctuary is carried within your own spine, freeing you to walk into any boardroom without shrinking.',
      interpersonalAndRomanticBonds: 'Allowing your partner to see your public triumph, balancing deep home intimacy with shared pride in your worldly stature.',
    },
  },
  '5-11': {
    axisName: 'The Axis of Creative Heart (5th) to Scaled Community Impact (11th)',
    karmicCeiling: 'Hoarding creative masterworks in private drawers, demanding exclusive aristocratic control, and fearing commercial scale.',
    rahuEvolutionaryCall: 'Monetizing your gifts at scale, building collaborative networks, and leading a broad community movement.',
    facetsShift: {
      vocationAndMoney: 'From sporadic solo consulting to scalable digital platforms, institutional syndicates, and recurring enterprise network revenue.',
      creativeVoiceAndVisibility: 'Translating your individual genius into collective movements, community educational frameworks, and mass impact.',
      somaticHealthAndNervousSystem: 'Releasing the high cardiac adrenaline spikes; grounding into cool, steady, sustainable peripheral nervous system regulation.',
      familyLineageAndAncestralRoles: 'Expanding beyond private family validation to create a chosen global tribe of aligned creators and allies.',
      existentialTrustAndSolitude: 'Feeling genuine belonging in humanity at large, recognizing that your unique gifts belong to the collective evolution.',
      interpersonalAndRomanticBonds: 'Balancing intense romantic devotion with shared involvement in a community mission that elevates both of you.',
    },
  },
  '6-12': {
    axisName: 'The Axis of Daily Service (6th) to Transpersonal Surrender (12th)',
    karmicCeiling: 'Compulsive operational micro-fixing, chronic hypochondria, administrative burnout, and treating life as an endless disaster drill.',
    rahuEvolutionaryCall: 'Surrendering to divine timing, cultivating deep restorative retreats, releasing hyper-control, and resting in timeless peace.',
    facetsShift: {
      vocationAndMoney: 'From grinding out 70-hour operational weeks to delegating mundane tasks, investing in automated systems, and prioritizing spacious vision.',
      creativeVoiceAndVisibility: 'Creating mythic, transcendent, and timeless work that speaks directly to the subconscious and spiritual depths of humanity.',
      somaticHealthAndNervousSystem: 'Releasing chronic digestive acid and adrenal burn; experiencing deep restorative sleep and cellular regeneration.',
      familyLineageAndAncestralRoles: 'Releasing the role of the family crisis fixer; allowing loved ones to navigate their own lessons while holding spiritual compassion.',
      existentialTrustAndSolitude: 'Experiencing profound trust in the unseen flow of existence, knowing that what is truly yours cannot be lost.',
      interpersonalAndRomanticBonds: 'Replacing diagnostic partner criticism with compassionate presence, holding space for imperfection without needing to repair it.',
    },
  },
  '7-1': {
    axisName: 'The Axis of Relational Fusion (7th) to Sovereign Self-Authorship (1st)',
    karmicCeiling: 'Subjugating your personal truth to maintain partnerships, living as a mirror for others, and abandoning your own vitality.',
    rahuEvolutionaryCall: 'Reclaiming your raw, instinctual individuality, physical assertion, and the courage to stand alone without apology.',
    facetsShift: {
      vocationAndMoney: 'From hiding behind co-founders to founding your own sovereign enterprise, taking solo risks, and claiming full equity.',
      creativeVoiceAndVisibility: 'Speaking with unedited, bold, and provocative authority; refusing to dilute your message for general consensus.',
      somaticHealthAndNervousSystem: 'Unclenching the sacral and pelvic floor; activating direct solar-plexus vitality, posture, and physical assertiveness.',
      familyLineageAndAncestralRoles: 'Breaking the codependent peacemaker role; refusing to compromise your values to keep relatives comfortable.',
      existentialTrustAndSolitude: 'Reconnecting with the sheer joy of individual existence, realizing that self-love is the foundation of all reality.',
      interpersonalAndRomanticBonds: 'Setting clean, immovable boundaries in intimacy; refusing to bargain away your identity in exchange for belonging.',
    },
  },
  '8-2': {
    axisName: 'The Axis of Crisis Entanglement (8th) to Grounded Self-Worth (2nd)',
    karmicCeiling: 'Addiction to psychological warfare, drama, trauma-bonding, and fear of sudden catastrophic betrayal.',
    rahuEvolutionaryCall: 'Building calm, sustainable, grounded material wealth, simple physical pleasures, and speaking your clear, unarmored truth.',
    facetsShift: {
      vocationAndMoney: 'From chaotic high-risk turnarounds to compounding steady, reliable, unshakeable assets and sustainable commercial stability.',
      creativeVoiceAndVisibility: 'Using your voice with resonant, grounded clarity rather than keeping your insights encrypted in subversive secrecy.',
      somaticHealthAndNervousSystem: 'Releasing the perpetual psoas fight-or-flight brace; sinking into physical relaxation, wholesome food, and sensory peace.',
      familyLineageAndAncestralRoles: 'Establishing a new lineage legacy of calm financial peace, ending generations of volatile financial and emotional swings.',
      existentialTrustAndSolitude: 'Discovering that ordinary peace is not boring; realizing that true spiritual mastery is living grounded on the physical earth.',
      interpersonalAndRomanticBonds: 'Choosing loyal, consistent, and predictable partners over volatile, intense trauma-bonds that drain your soul.',
    },
  },
  '9-3': {
    axisName: 'The Axis of Philosophical Ivory Tower (9th) to Grounded Tactical Courage (3rd)',
    karmicCeiling: 'Escaping into abstract dogmas, high-minded moral lecturing, and philosophical hermitage while avoiding practical execution.',
    rahuEvolutionaryCall: 'Getting your hands dirty in commercial enterprise, speaking directly in concise lay language, and executing decisive action.',
    facetsShift: {
      vocationAndMoney: 'From theoretical academic concepts to launching tangible commercial products, agile businesses, and rapid market experiments.',
      creativeVoiceAndVisibility: 'Translating complex cosmic concepts into punchy, electrifying, practical tools that ordinary people can use immediately.',
      somaticHealthAndNervousSystem: 'Activating hand-eye coordination, physical dexterity, and direct tactical vitality rather than sedentary contemplation.',
      familyLineageAndAncestralRoles: 'Relating to siblings and peers as authentic companions without needing to play the moralizing guru or righteous judge.',
      existentialTrustAndSolitude: 'Finding the sacred in daily conversations, craftsmanship, and local community rather than distant monasteries.',
      interpersonalAndRomanticBonds: 'Communicating everyday emotional needs in plain, direct language without hiding behind high philosophical metaphors.',
    },
  },
  '10-4': {
    axisName: 'The Axis of Executive Armor (10th) to Vulnerable Domestic Sanctuary (4th)',
    karmicCeiling: 'Sacrificing health, home, and emotional depth on the altar of public prestige, corporate titles, and external validation.',
    rahuEvolutionaryCall: 'Cultivating true emotional resting peace, tending your inner child, creating a loving home, and prioritizing resting health.',
    facetsShift: {
      vocationAndMoney: 'Redefining success: shifting from relentless status pursuit to sustainable businesses that nourish your private lifestyle and home.',
      creativeVoiceAndVisibility: 'Infusing your public offerings with raw emotional heart and vulnerability, moving people through soul connection.',
      somaticHealthAndNervousSystem: 'Releasing the chronic joint and knee pressure of workaholism; honoring deep restorative naps and emotional down-regulation.',
      familyLineageAndAncestralRoles: 'Healing ancestral mother wounds; creating a home environment characterized by unconditional warmth and presence.',
      existentialTrustAndSolitude: 'Resting in the knowledge that your worth was never determined by a resume, discovering sacred sanctuary within.',
      interpersonalAndRomanticBonds: 'Taking off the executive suit at the front door; welcoming your spouse or partner into your soft, unarmored vulnerability.',
    },
  },
  '11-5': {
    axisName: 'The Axis of Mass Collectivism (11th) to Sovereign Creative Radiance (5th)',
    karmicCeiling: 'Hiding behind committees, peer consensus, and large social networks while neglecting your personal creative spark.',
    rahuEvolutionaryCall: 'Stepping into the spotlight as an individual creator, trusting your heart intelligence, and taking romantic and creative leaps.',
    facetsShift: {
      vocationAndMoney: 'From anonymous network participation to building an eponymous brand, creative studio, or solo enterprise that celebrates your genius.',
      creativeVoiceAndVisibility: 'Releasing bold, singular, author-driven creations that don’t ask for committee approval or group consensus.',
      somaticHealthAndNervousSystem: 'Opening the chest and thoracic spine; allowing the heart to beat with passionate joy and spontaneous physical play.',
      familyLineageAndAncestralRoles: 'Breaking the mold of conforming to societal expectations; becoming the expressive, joyful artist of the lineage.',
      existentialTrustAndSolitude: 'Reconnecting with child-like wonder and creative play, finding God in personal joy rather than political movements.',
      interpersonalAndRomanticBonds: 'Welcoming intoxicating romance, romantic playfulness, and direct heart-to-heart adoration with an intimate partner.',
    },
  },
  '12-6': {
    axisName: 'The Axis of Mystical Dissolution (12th) to Grounded Somatic Mastery (6th)',
    karmicCeiling: 'Escaping into spiritual bypass, passive ungrounded drift, chaotic finances, and neglecting the physical body.',
    rahuEvolutionaryCall: 'Mastering daily practical routines, somatic health, financial budgeting, and rendering grounded service to the living world.',
    facetsShift: {
      vocationAndMoney: 'From vague, ungrounded artistic dreams to clean operational systems, precise contracts, and profitable daily execution.',
      creativeVoiceAndVisibility: 'Grounding high mystical visions into concrete, actionable books, curriculum, software, or health methodologies.',
      somaticHealthAndNervousSystem: 'Transforming ungrounded fatigue into robust immune resilience, daily physical movement, and clean nutritional rhythms.',
      familyLineageAndAncestralRoles: 'Ending lineage patterns of helplessness, addiction, or escapism; becoming the physically reliable anchor of the family.',
      existentialTrustAndSolitude: 'Finding the divine in the precision of the present moment—washing dishes, balancing budgets, and serving living beings.',
      interpersonalAndRomanticBonds: 'Showing love through tangible daily acts of service, punctuality, and clear agreements rather than dreamy promises.',
    },
  },
};

export interface SaturnManagerHouseProfile {
  houseNumber: number;
  managerTitle: string;
  focusArena: string;
  coreVigilanceRule: string;
  somaticLocation: string;
  facets: LifeFacetsImpact;
  weeklyWorkdayScenario: string;
}

export const SATURN_MANAGER_HOUSE_DATA: Record<number, SaturnManagerHouseProfile> = {
  1: {
    houseNumber: 1,
    managerTitle: 'The Sovereign Sentry of Tanu Bhava',
    focusArena: 'physical composure, personal reputation, and personal sovereignty',
    coreVigilanceRule: 'Never show physical fatigue, confusion, or emotional vulnerability in public; project unyielding poise.',
    somaticLocation: 'facial masking muscles, jawline, and cervical spine',
    facets: {
      vocationAndMoney: 'You position yourself as the ultimate authority figure who needs no supervision; delegating feels like relinquishing command.',
      creativeVoiceAndVisibility: 'Strictly polished and dignified; you edit out all quirky or chaotic impulses to maintain a commanding presence.',
      somaticHealthAndNervousSystem: 'Rigid posture and muscular bracing; you force your body through physical sickness using sheer willpower.',
      familyLineageAndAncestralRoles: 'The unbending pillar of the family who everyone expects to remain calm and decisive during disasters.',
      existentialTrustAndSolitude: 'Struggles with spontaneous surrender; treats meditation like an endurance exercise in stoic concentration.',
      interpersonalAndRomanticBonds: 'Presents a calm, unruffled facade to partners, hiding insecurity behind a wall of steady competence.',
    },
    weeklyWorkdayScenario: 'In meetings, your Manager monitors your posture, vocal timbre, and facial expressions, refusing to admit when a project timeline is unrealistic because acknowledging strain feels like defeat.',
  },
  2: {
    houseNumber: 2,
    managerTitle: 'The Conservative Auditor of Dhana Bhava',
    focusArena: 'liquid wealth, speech control, and material solvency',
    coreVigilanceRule: 'Guard every word and every dollar; never commit to speculative investments or unguarded verbal disclosures.',
    somaticLocation: 'throat, vocal chords, and mandibular clench',
    facets: {
      vocationAndMoney: 'Meticulous financial oversight; building fortress balance sheets and double-auditing every invoice and contract.',
      creativeVoiceAndVisibility: 'Measured, diplomatic, and conservative speech; you weigh every word to ensure it cannot damage your commercial standing.',
      somaticHealthAndNervousSystem: 'Chronic throat constriction and jaw aching; holding tension around vocal assertion and material security.',
      familyLineageAndAncestralRoles: 'The custodian of family wealth and estate paperwork, resisting relatives’ requests for reckless financial loans.',
      existentialTrustAndSolitude: 'Replaces spiritual faith with spreadsheets; feels existential ease only when emergency accounts are topped off.',
      interpersonalAndRomanticBonds: 'Demands absolute financial and domestic transparency from partners before letting emotional intimacy grow.',
    },
    weeklyWorkdayScenario: 'You review monthly expenses line-by-line late at night, feeling a quiet satisfaction when budget variance is zero, while your throat aches from holding back blunt truths all day.',
  },
  3: {
    houseNumber: 3,
    managerTitle: 'The Tactical Scribe of Sahaja Bhava',
    focusArena: 'documentation precision, tactical execution, and contractual defense',
    coreVigilanceRule: 'Document every decision in writing; out-prepare every opponent through superior research and technical diligence.',
    somaticLocation: 'shoulders, arms, wrists, and upper respiratory tract',
    facets: {
      vocationAndMoney: 'You produce exhaustive documentation, technical briefs, and strategic roadmaps to ensure no blame can ever land on your desk.',
      creativeVoiceAndVisibility: 'Heavily researched, intellectualized prose; you cite sources and empirical evidence to preemptively silence critics.',
      somaticHealthAndNervousSystem: 'Tension headaches, eye strain, and shallow breathing from sitting over keyboards drafting detailed defenses.',
      familyLineageAndAncestralRoles: 'The family administrator who drafts the wills, organizes the medical records, and handles contentious sibling paperwork.',
      existentialTrustAndSolitude: 'Can only rest if tomorrow’s tactical schedule is printed, confirmed, and color-coded.',
      interpersonalAndRomanticBonds: 'Answers emotional questions with detailed logical arguments, leaving partners frustrated by your courtroom precision.',
    },
    weeklyWorkdayScenario: 'You spend an extra 90 minutes proofreading a 10-page technical specification to ensure not a single comma or clause can be faulted by auditors or clients.',
  },
  4: {
    houseNumber: 4,
    managerTitle: 'The Fortress Warden of Sukha Bhava',
    focusArena: 'domestic stability, private emotional lockdown, and home containment',
    coreVigilanceRule: 'Keep the home container strictly organized and emotionally protected; do not let chaotic outside drama breach the nest.',
    somaticLocation: 'sub-diaphragm, stomach lining, and lower thoracic spine',
    facets: {
      vocationAndMoney: 'You anchor career success to real estate and domestic equity; career moves are vetted for whether they protect home peace.',
      creativeVoiceAndVisibility: 'Private, guarded creative rhythm; you only share work once it has been safely incubated inside your private sanctuary.',
      somaticHealthAndNervousSystem: 'Stomach clenching and insomnia when home peace is disturbed; needs orderly surroundings to regulate.',
      familyLineageAndAncestralRoles: 'The structural anchor who maintains the family home, elders, and domestic rituals regardless of personal fatigue.',
      existentialTrustAndSolitude: 'Spiritual sanctuary is found in a quiet, spotless room with doors locked and phones silenced.',
      interpersonalAndRomanticBonds: 'Strict domestic routines; expects a partner to respect private boundaries and keep emotional volatility outside.',
    },
    weeklyWorkdayScenario: 'You walk through your living space tidying up every stray object and double-checking door locks before you can even begin to decompress from an exhausting work week.',
  },
  5: {
    houseNumber: 5,
    managerTitle: 'The Academic Architect of Putra Bhava',
    focusArena: 'creative methodology, structured genius, and measured risk',
    coreVigilanceRule: 'Never release amateur, spontaneous, or unpolished creations; turn inspiration into disciplined mastery.',
    somaticLocation: 'cardiac center, upper back, and thoracic spine',
    facets: {
      vocationAndMoney: 'You channel creative vision into rigorous frameworks, educational curriculums, and methodically de-risked ventures.',
      creativeVoiceAndVisibility: 'Formal, dignified, and architectonic; you strip away silly or frivolous elements to ensure intellectual gravitas.',
      somaticHealthAndNervousSystem: 'Cardiac tension under performance review; treats creative work with the solemnity of a high-stakes exam.',
      familyLineageAndAncestralRoles: 'The family mentor who sets high academic and creative standards for children or younger relatives.',
      existentialTrustAndSolitude: 'Engages in serious creative research during solitude, reading dense classical texts rather than relaxing.',
      interpersonalAndRomanticBonds: 'Slow-burning romantic pacing; requires deep respect for your intellect before romantic romance can bloom.',
    },
    weeklyWorkdayScenario: 'You spend months structuring a creative offering into a 12-stage curriculum, refusing to launch a pilot program until every diagram and workbook page is flawless.',
  },
  6: {
    houseNumber: 6,
    managerTitle: 'The Relentless Field Commander of Ripu Bhava',
    focusArena: 'operational debugging, crisis prevention, and systemic labor',
    coreVigilanceRule: 'Expect friction, disorder, and flaws; out-work the chaos through relentless daily discipline and early intervention.',
    somaticLocation: 'gut microbiome, lower abdomen, and lumbar spine',
    facets: {
      vocationAndMoney: 'The master technician who fixes broken departments, eliminates operational waste, and thrives under grueling deadlines.',
      creativeVoiceAndVisibility: 'Focuses on pragmatic problem-solving tools, diagnostic manuals, and practical utility rather than decorative art.',
      somaticHealthAndNervousSystem: 'Adrenal exhaustion and gastrointestinal stress; you run on black coffee and adrenaline until forced to bed.',
      familyLineageAndAncestralRoles: 'The designated family caregiver and problem-solver who takes on the exhausting eldercare and medical crises.',
      existentialTrustAndSolitude: 'Struggles deeply with unstructured rest; feels that taking a day off is an invitation for operational catastrophe.',
      interpersonalAndRomanticBonds: 'Shows affection through practical service and troubleshooting partner problems rather than soft emotional words.',
    },
    weeklyWorkdayScenario: 'You work through lunch debugging a systemic software or logistical error, determined that your operational unit will meet its deadline regardless of teammate attrition.',
  },
  7: {
    houseNumber: 7,
    managerTitle: 'The Chief Negotiator of Yuvati Bhava',
    focusArena: 'contractual equity, public diplomacy, and bilateral terms',
    coreVigilanceRule: 'Structure every partnership with ironclad legal protections; assume contracts will be tested in adversity.',
    somaticLocation: 'sacroiliac joint, hips, and lower back',
    facets: {
      vocationAndMoney: 'You demand written contracts, clear scopes of work, and strict performance milestones before entering any joint business.',
      creativeVoiceAndVisibility: 'Diplomatic, balanced, and peer-reviewed; you ensure your public communications offend no major stakeholders.',
      somaticHealthAndNervousSystem: 'Lower back stiffness from holding diplomatic composure during contentious negotiations.',
      familyLineageAndAncestralRoles: 'The fair, impartial arbiter who negotiates family inheritance divisions and resolves long-standing marital feuds.',
      existentialTrustAndSolitude: 'Exhausted by constant social diplomacy; seeks total isolation to drop the mask of the fair negotiator.',
      interpersonalAndRomanticBonds: 'Treats marriage like a formal covenant; values shared life logistics and reliability over passionate volatility.',
    },
    weeklyWorkdayScenario: 'During partner negotiations, you remain completely calm and poker-faced while quietly insisting on revised clause language that prevents you from being cut out of royalties.',
  },
  8: {
    houseNumber: 8,
    managerTitle: 'The Risk Sentinel of Randhra Bhava',
    focusArena: 'crisis reserves, secret assets, and existential hedging',
    coreVigilanceRule: 'Prepare for worst-case catastrophes, market collapses, and institutional betrayals; keep reserve power hidden.',
    somaticLocation: 'pelvic basin, deep psoas, and adrenal glands',
    facets: {
      vocationAndMoney: 'You build unshakeable survival funds, hedge portfolios, and confidential alliances that keep you solvent in a crash.',
      creativeVoiceAndVisibility: 'Profound, penetrative, and secretive; you disclose insights with surgical timing while withholding your core secrets.',
      somaticHealthAndNervousSystem: 'Psoas muscle hyper-vigilance; scanning every environment for psychological and financial booby-traps.',
      familyLineageAndAncestralRoles: 'The trusted custodian of the family’s deepest secrets, financial trusts, and sensitive estate realities.',
      existentialTrustAndSolitude: 'Thrives in private shadows; you feel most secure when competitors and relatives have no idea what you own.',
      interpersonalAndRomanticBonds: 'Takes years to grant full emotional trust, requiring partners to demonstrate unshakeable loyalty in crises.',
    },
    weeklyWorkdayScenario: 'You set up redundant backup servers, encrypted financial keys, and secondary bank lines, ensuring that even if your primary partner defaults, your lifestyle will continue uninterrupted.',
  },
  9: {
    houseNumber: 9,
    managerTitle: 'The Ethical Magistrate of Dharma Bhava',
    focusArena: 'philosophical integrity, moral governance, and institutional legitimacy',
    coreVigilanceRule: 'Hold the highest ethical standard; ensure every project is legally, morally, and philosophically unassailable.',
    somaticLocation: 'hips, sciatic nerve, and thighs',
    facets: {
      vocationAndMoney: 'You build enterprises on ethical rock; refusing short-term profits that could compromise your long-term moral standing.',
      creativeVoiceAndVisibility: 'Authoritative, philosophical, and judicial; you write with the weight of tradition, ethical codes, and higher principles.',
      somaticHealthAndNervousSystem: 'Sciatic irritation and hip tension when forced to comply with unethical corporate mandates.',
      familyLineageAndAncestralRoles: 'The moral conscience of the family who insists on integrity, academic rigor, and principled conduct.',
      existentialTrustAndSolitude: 'Finds peace in studying profound philosophical texts and contemplating universal cosmic laws.',
      interpersonalAndRomanticBonds: 'Needs a partner who shares your moral integrity and worldview, feeling repulsed by pettiness or cynicism.',
    },
    weeklyWorkdayScenario: 'You refuse a multi-million-dollar sponsorship or commercial partnership because the sponsor’s corporate practices violate your internal ethical code, sleeping soundly despite lost revenue.',
  },
  10: {
    houseNumber: 10,
    managerTitle: 'The Executive Sovereign of Karma Bhava',
    focusArena: 'career prestige, institutional authority, and public reputation',
    coreVigilanceRule: 'Never let public reputation falter; maintain unquestioned professional competence and executive composure.',
    somaticLocation: 'knees, skeletal frame, upper trapezius, and neck',
    facets: {
      vocationAndMoney: 'You out-work everyone in the executive suite, logging 60-hour weeks to cement your status as indispensable leadership.',
      creativeVoiceAndVisibility: 'Polished, authoritative, and corporate-ready; you present yourself as a master of your industry.',
      somaticHealthAndNervousSystem: 'Skeletal fatigue, knee stiffness, and chronic neck tightness from carrying the weight of institutional expectations.',
      familyLineageAndAncestralRoles: 'The flagship achiever of the family lineage who bears the responsibility of elevating the family name.',
      existentialTrustAndSolitude: 'Struggles to turn off the executive brain; identity feels hollow unless tied to an active, prestigious campaign.',
      interpersonalAndRomanticBonds: 'Compartmentalizes home life around career priorities, needing a partner who understands your vocational drive.',
    },
    weeklyWorkdayScenario: 'You arrive at the boardroom having memorized the quarterly financial models, fielding hostile shareholder questions with ice-cold poise while your knee aches beneath the table.',
  },
  11: {
    houseNumber: 11,
    managerTitle: 'The Network Strategist of Labha Bhava',
    focusArena: 'large-scale community distribution, revenue pipelines, and alliance capital',
    coreVigilanceRule: 'Maintain strategic relationships across multiple networks; ensure revenue flows through diversified collective channels.',
    somaticLocation: 'calves, shins, ankles, and peripheral nerves',
    facets: {
      vocationAndMoney: 'You build strategic alliances and network syndicates, monetizing collective reach while protecting your individual equity.',
      creativeVoiceAndVisibility: 'Speaks the language of systems, collective impact, and community movements, carefully managing group politics.',
      somaticHealthAndNervousSystem: 'Peripheral nervous agitation and ankle stiffness from non-stop social coordination and digital networking.',
      familyLineageAndAncestralRoles: 'The connector who links the family to prominent outside institutions, schools, and business guilds.',
      existentialTrustAndSolitude: 'Finds meaning in building platforms that outlive your individual ego, serving long-term social evolution.',
      interpersonalAndRomanticBonds: 'Balances partnership with an expansive circle of colleagues and causes, requiring a partner who values freedom.',
    },
    weeklyWorkdayScenario: 'You coordinate a multi-stakeholder symposium or cross-departmental alliance, managing delicate political egos with calm diplomacy to ensure funding goals are met.',
  },
  12: {
    houseNumber: 12,
    managerTitle: 'The Solitary Cloister of Vyaya Bhava',
    focusArena: 'subconscious containment, energetic boundaries, and quiet asylum',
    coreVigilanceRule: 'Protect your energetic aura from worldly noise; manage retreat and subconscious restoration with strict boundaries.',
    somaticLocation: 'feet, pineal/melatonin sleep rhythms, and lymphatic system',
    facets: {
      vocationAndMoney: 'You work best in secluded, private laboratories, studies, or offshore ventures, away from noisy open-plan offices.',
      creativeVoiceAndVisibility: 'Mystic, poetic, and enigmatic; you publish from behind a veil of privacy, letting the work speak for itself.',
      somaticHealthAndNervousSystem: 'Sleep sensitivity and lymphatic stagnation; you require complete sensory deprivation to down-regulate.',
      familyLineageAndAncestralRoles: 'The quiet relative who lives at a distance, holding peaceful energetic space for the family without entering daily drama.',
      existentialTrustAndSolitude: 'Spiritual solitude is your natural home; you recharge through deep meditation, dreamwork, and nature.',
      interpersonalAndRomanticBonds: 'Requires massive amounts of private space within partnership; loves deeply but needs regular periods of total seclusion.',
    },
    weeklyWorkdayScenario: 'You slip away from a crowded professional conference at 8 PM, retreating to your hotel room to meditate in silence, refusing late-night bar networking to preserve your sanity.',
  },
};

export const MARS_FIREFIGHTER_HOUSE_DATA: Record<number, {
  houseNumber: number;
  firefighterTitle: string;
  emergencyTrigger: string;
  emergencyAction: string;
  facets: LifeFacetsImpact;
}> = {
  1: {
    houseNumber: 1,
    firefighterTitle: 'The Sovereign Battering Ram (1st Bhava)',
    emergencyTrigger: 'When someone attempts to physically or psychologically dominate, trap, or micromanage you.',
    emergencyAction: 'Sudden, ferocious physical boundary assertion: walking out of the building, cutting ties instantly, or erupting in raw defiance.',
    facets: {
      vocationAndMoney: 'Abruptly walking off a project or submitting an immediate resignation when an executive oversteps personal boundaries.',
      creativeVoiceAndVisibility: 'Publishing raw, unedited, and provocative statements that shatter polite decorum to reclaim your authenticity.',
      somaticHealthAndNervousSystem: 'Adrenaline surges, chest heat, and immediate physical restlessness demanding hard athletic discharge.',
      familyLineageAndAncestralRoles: 'Fiercely cutting off guilt-tripping relatives, refusing to be parentified or managed any longer.',
      existentialTrustAndSolitude: 'Reclaiming absolute solitary sovereignty: "I was born alone and I will stand alone without apology."',
      interpersonalAndRomanticBonds: 'Packing a bag and leaving during an argument when feeling cornered or emotionally manipulated.',
    },
  },
  2: {
    houseNumber: 2,
    firefighterTitle: 'The Scorched-Earth Sentry (2nd Bhava)',
    emergencyTrigger: 'When someone threatens your material livelihood, exploits your assets, or attempts to silence your voice.',
    emergencyAction: 'Savage verbal takedown followed by locking down all financial assets, cutting off financial support, or impulsive compensatory spending.',
    facets: {
      vocationAndMoney: 'Pulling all capital out of a joint venture overnight or spending a large sum on an escape to break financial anxiety.',
      creativeVoiceAndVisibility: 'Delivering scathing, unvarnished verbal critiques that burn commercial bridges clean.',
      somaticHealthAndNervousSystem: 'Burning throat heat, rapid speech, and digestive acid flare-ups under extreme economic stress.',
      familyLineageAndAncestralRoles: 'Severing financial ties with demanding relatives, refusing to be the family’s emergency bank.',
      existentialTrustAndSolitude: 'Retreating into austere financial self-reliance, declaring you need nothing from anyone.',
      interpersonalAndRomanticBonds: 'Going completely silent and cutting joint card access when feeling financially disrespected by a partner.',
    },
  },
  3: {
    houseNumber: 3,
    firefighterTitle: 'The Tactical Blitzkrieg (3rd Bhava)',
    emergencyTrigger: 'When someone tries to humiliate your intellect, manipulate communication, or stall your decisive progress.',
    emergencyAction: 'Blistering electronic rebuttals, aggressive public exposés, or ruthlessly blocking contacts across all channels.',
    facets: {
      vocationAndMoney: 'Sending a scorching, evidence-heavy email that dismantles an incompetent supervisor or competitor in public.',
      creativeVoiceAndVisibility: 'Deleting digital platforms in a fit of disgust, or releasing a brutal critique of industry hypocrisy.',
      somaticHealthAndNervousSystem: 'Intense neural agitation, rapid typing, shallow breathing, and hand tremors from adrenaline.',
      familyLineageAndAncestralRoles: 'Directly confronting sibling favoritism with blistering honesty, refusing to pretend peace exists.',
      existentialTrustAndSolitude: 'Going off the grid, throwing your phone into a drawer, and refusing all digital communication for 72 hours.',
      interpersonalAndRomanticBonds: 'Firing off ten rapid text messages dissecting a partner’s inconsistency, then turning your phone off.',
    },
  },
  4: {
    houseNumber: 4,
    firefighterTitle: 'The Fortress Breaker (4th Bhava)',
    emergencyTrigger: 'When domestic peace is repeatedly violated, emotional safety is crushed, or home becomes a prison.',
    emergencyAction: 'Slamming doors, leaving the home abruptly, renting a separate apartment, or emotionally freezing out housemates.',
    facets: {
      vocationAndMoney: 'Abandoning a high-paying job that requires you to sacrifice your home sanctuary and mental health.',
      creativeVoiceAndVisibility: 'Retreating completely into private creative exile, refusing to commercialize your personal work.',
      somaticHealthAndNervousSystem: 'Violent stomach knots, emotional weeping, or sudden physical lethargy forcing days in bed.',
      familyLineageAndAncestralRoles: 'Setting an immovable boundary with invasive parents, refusing to answer the door or phone.',
      existentialTrustAndSolitude: 'Locking yourself in your room with curtains drawn, needing absolute sensory darkness to recover.',
      interpersonalAndRomanticBonds: 'Sleeping on the couch or checking into a hotel when intimate friction makes home unbearable.',
    },
  },
  5: {
    houseNumber: 5,
    firefighterTitle: 'The Wildfire Artist (5th Bhava)',
    emergencyTrigger: 'When your creative soul is mocked, commercialized into banality, or romantic trust is betrayed.',
    emergencyAction: 'Destroying unfinished canvases, shelving multi-year projects, or ending a romantic bond with operatic finality.',
    facets: {
      vocationAndMoney: 'Ripping up contracts with clients who demand you dilute your creative vision for mass market mediocrity.',
      creativeVoiceAndVisibility: 'Burning manuscripts or deleting years of content in a fit of disgust: "If it cannot be pure, it won’t exist."',
      somaticHealthAndNervousSystem: 'Acute heart ache, chest heat, and sudden emotional storms demanding expressive physical release.',
      familyLineageAndAncestralRoles: 'Rejecting family expectations of a conventional career, defiantly pursuing an unconventional artistic path.',
      existentialTrustAndSolitude: 'Dramatic solitary retreats where you plunge into intense creative creation or complete silence.',
      interpersonalAndRomanticBonds: 'Delivering an unforgettable parting speech and walking away from a lover without looking back.',
    },
  },
  6: {
    houseNumber: 6,
    firefighterTitle: 'The Systemic Saboteur (6th Bhava)',
    emergencyTrigger: 'When workplace exploitation becomes unlivable, unfair debts mount, or bureaucratic gaslighting occurs.',
    emergencyAction: 'Filing aggressive formal grievances, organizing labor strikes, or walking off an operational shift in cold mutiny.',
    facets: {
      vocationAndMoney: 'Exposing corrupt workplace practices to compliance boards, burning down toxic executive hierarchies.',
      creativeVoiceAndVisibility: 'Publishing unflinching diagnostic exposés that lay bare institutional dysfunction.',
      somaticHealthAndNervousSystem: 'Sudden autoimmune flare-up or acute exhaustion that physically disables you from working another hour.',
      familyLineageAndAncestralRoles: 'Resigning from the family caregiver role, letting other family members face the consequences of their neglect.',
      existentialTrustAndSolitude: 'Exhausted collapse into solitary physical sleep, refusing to answer any demands or requests for help.',
      interpersonalAndRomanticBonds: 'Presenting a partner with an uncompromising list of behavioral changes or ending the relationship.',
    },
  },
  7: {
    houseNumber: 7,
    firefighterTitle: 'The Severed Covenant (7th Bhava)',
    emergencyTrigger: 'When a business co-founder or spouse cheats, exploits your trust, or attempts to absorb your sovereignty.',
    emergencyAction: 'Immediate contract dissolution, asset freezing, filing for divorce, or cold, unyielding legal severance.',
    facets: {
      vocationAndMoney: 'Dissolving a multi-million-dollar partnership overnight, taking your client list and starting from scratch.',
      creativeVoiceAndVisibility: 'Reclaiming your solo identity, rebranding your name and refusing to share credit with former collaborators.',
      somaticHealthAndNervousSystem: 'Acute pelvic and lumbar pain dissolving into clean, sharp adrenaline once the toxic cord is cut.',
      familyLineageAndAncestralRoles: 'Refusing to attend family events where abusive spouses or toxic in-laws are accommodated.',
      existentialTrustAndSolitude: 'Radical return to singlehood, celebrating solitary autonomy as a sacred, unpolluted state.',
      interpersonalAndRomanticBonds: 'Cold, glacial emotional disconnect; when you are done with a partner, they cease to exist in your heart.',
    },
  },
  8: {
    houseNumber: 8,
    firefighterTitle: 'The Phoenix Detonator (8th Bhava)',
    emergencyTrigger: 'When hidden conspiracies surface, psychological blackmail is attempted, or catastrophic loss looms.',
    emergencyAction: 'Total psychological scorched earth: unveiling all hidden secrets, destroying leverage, and rising from the ashes.',
    facets: {
      vocationAndMoney: 'Blowing the whistle on corrupt business partners, accepting temporary financial chaos to destroy their hold on you.',
      creativeVoiceAndVisibility: 'Releasing explosive, taboo-shattering work that forces a complete reckoning in your industry.',
      somaticHealthAndNervousSystem: 'Deep psoas tremor and intense somatic discharge as years of suppressed rage surface.',
      familyLineageAndAncestralRoles: 'Exposing multi-generational family secrets—affairs, financial deceit, or abuse—ending the conspiracy of silence.',
      existentialTrustAndSolitude: 'Total psychological shedding: changing your appearance, moving cities, and starting a completely new life.',
      interpersonalAndRomanticBonds: 'Confronting an unfaithful partner with undeniable forensic evidence, cutting ties with terrifying finality.',
    },
  },
  9: {
    houseNumber: 9,
    firefighterTitle: 'The Iconoclast (9th Bhava)',
    emergencyTrigger: 'When spiritual mentors turn out to be charlatans, institutions preach hypocrisy, or dogmas restrict freedom.',
    emergencyAction: 'Public apostasy, denouncing hypocritical organizations, leaving religious orders, or emigrating to a foreign land.',
    facets: {
      vocationAndMoney: 'Walking away from prestigious academic or institutional chairs because leadership sold out to corporate lobbies.',
      creativeVoiceAndVisibility: 'Writing fierce, iconoclastic critiques that dismantle sacred cows and expose spiritual materialism.',
      somaticHealthAndNervousSystem: 'Restless travel impulses; pacing floors and feeling physical claustrophobia when confined by dogma.',
      familyLineageAndAncestralRoles: 'Formally rejecting traditional family religious rituals, establishing your own ethical compass.',
      existentialTrustAndSolitude: 'Seeking God in the untamed wilderness or foreign deserts, far from human temples and churches.',
      interpersonalAndRomanticBonds: 'Ending bonds with partners who adopt dogmatic, self-righteous, or morally condescending attitudes.',
    },
  },
  10: {
    houseNumber: 10,
    firefighterTitle: 'The Throne Abdicator (10th Bhava)',
    emergencyTrigger: 'When career prestige demands you become a soulless corporate automaton or sacrifice your core integrity.',
    emergencyAction: 'Shock public resignation from top executive posts, declining prestigious awards, or walking away at the peak of power.',
    facets: {
      vocationAndMoney: 'Giving up a lucrative C-suite salary to regain your soul, walking out on a toxic corporate empire.',
      creativeVoiceAndVisibility: 'Rejecting corporate marketing teams, producing unvarnished, raw independent work outside the mainstream.',
      somaticHealthAndNervousSystem: 'Immediate physical relief in knees and spine when dropping the crushing burden of executive prestige.',
      familyLineageAndAncestralRoles: 'Telling parents that you will no longer live their dream of corporate glory, claiming your own life.',
      existentialTrustAndSolitude: 'Relishing the freedom of being an "ordinary nobody" after years of exhausting public performance.',
      interpersonalAndRomanticBonds: 'Reconnecting with authentic intimacy once you no longer need your spouse to be an accessory to your status.',
    },
  },
  11: {
    houseNumber: 11,
    firefighterTitle: 'The Exile from the Tribe (11th Bhava)',
    emergencyTrigger: 'When peer groups engage in mob mentality, groupthink stifles individuality, or allies collude behind your back.',
    emergencyAction: 'Mass-unsubscribing, deleting social profiles, resigning from boards, and walking out of collective alliances.',
    facets: {
      vocationAndMoney: 'Pulling your products from large distribution platforms to sell directly and independently to true patrons.',
      creativeVoiceAndVisibility: 'Writing blistering polemics against industry consensus and herd mentality.',
      somaticHealthAndNervousSystem: 'Dropping electrical nervous tension; experiencing deep physical peace when unplugged from social feeds.',
      familyLineageAndAncestralRoles: 'Refusing to attend large family clan gatherings where individual truth is swallowed by clan loyalty.',
      existentialTrustAndSolitude: 'Embracing the role of the solitary scout who walks far ahead of the tribe, unburdened by consensus.',
      interpersonalAndRomanticBonds: 'Cutting out superficial social circles to spend intimate, quiet evenings with one true soul companion.',
    },
  },
  12: {
    houseNumber: 12,
    firefighterTitle: 'The Ghost in the Mist (12th Bhava)',
    emergencyTrigger: 'When sensory overload, corporate noise, and worldly demands threaten total psychic breakdown.',
    emergencyAction: 'Total vanishing act: turning off phones, booking a remote hermitage cabin, and disappearing into silence for weeks.',
    facets: {
      vocationAndMoney: 'Taking a complete sabbatical, letting commercial projects pause while you restore your energetic boundaries.',
      creativeVoiceAndVisibility: 'Going completely silent; refusing all interviews, podcasts, or marketing, letting your presence fade into myth.',
      somaticHealthAndNervousSystem: 'Entering deep hibernatory sleep, taking warm salt baths, and walking barefoot on the earth to discharge stress.',
      familyLineageAndAncestralRoles: 'Becoming completely unreachable to demanding relatives, putting up an impenetrable energetic shield.',
      existentialTrustAndSolitude: 'Floating in transpersonal surrender, remembering that this temporary worldly life is but a passing dream.',
      interpersonalAndRomanticBonds: 'Needing partners to respect total non-verbal silence for days at a time to allow your soul to reassemble.',
    },
  },
};

